import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary': '#ffffff',
        'tertiary': '#555744',
        'surface-dim': '#dadada',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'on-surface': '#1a1c1c',
        'outline': '#737686',
        'surface-container-low': '#f3f3f3',
        'surface-bright': '#f9f9f9',
        'on-primary-container': '#eeefff',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        'primary-container': '#2563eb',
        'inverse-on-surface': '#f0f1f1',
        'secondary-fixed': '#d5e3fc',
        'on-secondary-container': '#57657a',
        'secondary-container': '#d5e3fc',
        'primary-fixed': '#dbe1ff',
        'on-background': '#1a1c1c',
        'on-primary': '#ffffff',
        'surface': '#f9f9f9',
        'inverse-surface': '#2f3131',
        'surface-tint': '#0053db',
        'tertiary-fixed': '#e4e4cc',
        'secondary': '#515f74',
        'on-primary-fixed': '#00174b',
        'inverse-primary': '#b4c5ff',
        'background': '#f9f9f9',
        'surface-container-highest': '#e2e2e2',
        'primary': '#004ac6',
        'on-secondary-fixed-variant': '#3a485b',
        'on-tertiary-fixed': '#1b1d0e',
        'on-error': '#ffffff',
        'on-secondary-fixed': '#0d1c2e',
        'tertiary-container': '#6e6f5b',
        'on-tertiary-fixed-variant': '#474836',
        'surface-variant': '#e2e2e2',
        'secondary-fixed-dim': '#b9c7df',
        'outline-variant': '#c3c6d7',
        'on-primary-fixed-variant': '#003ea8',
        'on-surface-variant': '#434655',
        'error-container': '#ffdad6',
        'on-tertiary-container': '#f2f2d9',
        'tertiary-fixed-dim': '#c8c8b0',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#b4c5ff',
        'error': '#ba1a1a',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      animation: {
        'pulse-light': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      boxShadow: {
        whisper: '0px 4px 20px rgba(0, 74, 198, 0.06)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}

export default config
