import { FormEvent, useState, useEffect } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { setAuthToken } from "../lib/auth";
import { verifyMfa } from "../lib/api";

export default function MfaChallengePage() {
  const navigate = useNavigate();
  const location = useLocation();
  const [otpCode, setOtpCode] = useState("");
  const [error, setError] = useState("");
  const [submitting, setSubmitting] = useState(false);

  // Extract navigation state or URL params (for OAuth redirects)
  const searchParams = new URLSearchParams(location.search);
  const mfaToken = location.state?.mfaToken || searchParams.get("mfa_token");
  const email = location.state?.email || searchParams.get("email");

  useEffect(() => {
    // If we reach this page without an MFA token, redirect back to login
    if (!mfaToken) {
      navigate("/login", { replace: true });
    }
  }, [mfaToken, navigate]);

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!mfaToken || otpCode.length < 6) return;
    
    setSubmitting(true);
    setError("");

    try {
      const response = await verifyMfa({ mfa_token: mfaToken, otp_code: otpCode });
      if (response.access_token) {
        setAuthToken(response.access_token);
        navigate("/dashboard");
      } else {
        setError("Final authentication failed. Please try logging in again.");
      }
    } catch (submitError) {
      const fallback = submitError instanceof Error ? submitError.message : "Invalid or expired verification code.";
      setError(fallback);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="login-screen">
      <div className="login-aura login-aura-top" style={{ opacity: 0.4 }} />
      <div className="login-aura login-aura-bottom" style={{ opacity: 0.4 }} />

      <main className="login-grid">
        <section className="login-brand-panel">
          <p className="eyebrow" style={{ color: "var(--brand-primary)" }}>Identity Verification</p>
          <h1 className="login-brand" style={{ fontSize: "3rem" }}>TOTP <br/>CHALLENGE.</h1>
          <span className="login-divider" />
          <p className="hero-copy">
            Please enter the 6-digit security code generated by your Authenticator App to establish this session.
          </p>
          <div className="meta-row">
            <div>
              <label>Method</label>
              <strong>Authenticator</strong>
            </div>
            <div>
              <label>Standard</label>
              <strong>RFC 6238</strong>
            </div>
          </div>
        </section>

        <section className="login-card" style={{ backdropFilter: "blur(20px)", padding: "3.5rem" }}>
          <p className="eyebrow">Challenge Phase 2/2</p>
          <h2 style={{ fontSize: "1.75rem", textTransform: "uppercase", letterSpacing: "1px" }}>Enter Code</h2>
          <p className="hero-copy" style={{ marginBottom: "2rem" }}>Enter your security token to finalize synchronization.</p>

          <form className="stack" onSubmit={handleSubmit}>
            <div style={{ position: "relative", marginBottom: "1.5rem" }}>
              <input
                autoFocus
                className="obs-input"
                id="otp"
                maxLength={6}
                onChange={(event) => setOtpCode(event.target.value.replace(/[^0-9]/g, ""))}
                placeholder="000000"
                required
                style={{ 
                  letterSpacing: "0.8rem", 
                  textAlign: "center", 
                  fontSize: "2.5rem", 
                  fontWeight: "700",
                  padding: "1rem",
                  border: "2px solid rgba(255,255,255,0.1)",
                  backgroundColor: "rgba(0,0,0,0.2)",
                  color: "var(--brand-primary)",
                  fontFamily: "monospace"
                }}
                type="text"
                value={otpCode}
              />
              <div style={{ 
                height: "2px", 
                backgroundColor: "var(--brand-primary)", 
                width: otpCode.length > 0 ? `${(otpCode.length / 6) * 100}%` : "0%",
                transition: "width 0.3s ease",
                marginTop: "4px"
              }} />
            </div>

            {error ? <p className="error-text" style={{ padding: "0.75rem", backgroundColor: "rgba(220, 53, 69, 0.1)", borderRadius: "4px" }}>{error}</p> : null}

            <button 
              className="btn btn-primary" 
              disabled={submitting || otpCode.length < 6} 
              type="submit"
              style={{ height: "55px", marginTop: "1rem" }}
            >
              {submitting ? "Verifying..." : "Confirm Identity"}
            </button>

            <button 
              className="plain-link" 
              onClick={() => navigate("/login")} 
              style={{ marginTop: "1.5rem", opacity: 0.6, fontSize: "0.8rem" }}
              type="button"
            >
              BACK TO SIGN IN
            </button>
          </form>
        </section>
      </main>
    </div>
  );
}
